version: "3.8"
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "DKPFrontEnd"
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - "/app/node_modules"
