version: "3.8"
services:
  frontend:
    container_name: "DKPFrontEnd"
    image: node:lts
    working_dir: /app
    entrypoint: /bin/bash
    env_file:
      - .env
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
