
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "DKPFrontEnd"
    ports:
      - '5173:5173'
    volumes:
      - DKPFrontEnd:/app
volumes:
  DKPFrontEnd:
    external: true
