version: "3.8"
services:
  vue_app_dev:
    build:
      dockerfile: dockerfiles/Dev.Dockerfile
    volumes:
      - DKPFrontEnd:/vue_app
    ports:
      - "5173:5173"
  vue_app_prod:
    image: earthenlynx/vue_app:production
    ports:
      - "5174:5174"
volumes:
  DKPFrontEnd:
    external: true