version: "3.8"
services:
  frontend:
    image: app
    build:
    context: .
    env_file: ".env"
    volumes:
       - '.:/app'
       - /app/node_modules/ 
    networks:
      - common
    expose:
      - 5173
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app.loadbalancer.server.port=5173"
      - "traefik.http.routers.app.rule=Host(`example.com`)"
