version: "3.8"
services:
  frontend:
    build: .
    container_name: "DKPFrontEnd"
    env_file:
      - .env
    expose: 
      - '5173'
    volumes:
      - .:/app
      - "/app/node_modules"
    networks:
      - common
